[project]
name = "comfyui-sonar"
description = "A janky implementation of Sonar sampling (momentum-based sampling) for ComfyUI."
version = "1.0.0"
license = "LICENSE"

[project.urls]
Repository = "https://github.com/blepping/ComfyUI-sonar"
#  Used by Comfy Registry https://comfyregistry.org

[tool.comfy]
PublisherId = ""
DisplayName = "ComfyUI-sonar"
Icon = ""
